export enum ErrorCode {
  // Generic
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_ROLES_INVALID = 'AUTH_ROLES_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Contact
  CONTACT_NOT_FOUND = 'CONTACT_NOT_FOUND',
  CONTACT_ALREADY_EXISTS = 'CONTACT_ALREADY_EXISTS',
  CONTACT_VALIDATION_FAILED = 'CONTACT_VALIDATION_FAILED',
  CONTACT_EMAIL_REQUIRED = 'CONTACT_EMAIL_REQUIRED',

  // File
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',

  // Storage
  STORAGE_OPERATION_FAILED = 'STORAGE_OPERATION_FAILED',
}
